# Generated by Django 6.0.5 on 2026-06-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_slide'),
    ]

    operations = [
        migrations.CreateModel(
            name='slides_no',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slides_no', models.IntegerField(max_length=10)),
                ('slide_time', models.IntegerField(max_length=100)),
            ],
        ),
    ]
