# Generated by Django 6.0.5 on 2026-06-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_slides_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slides_no',
            name='slide_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='slides_no',
            name='slides_no',
            field=models.IntegerField(),
        ),
    ]
