# Generated by Django 6.0.5 on 2026-06-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_alter_slides_no_slide_time_alter_slides_no_slides_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('contain', models.CharField(max_length=500)),
                ('ids', models.CharField(max_length=100)),
            ],
        ),
    ]
