# Generated by Django 6.0.5 on 2026-06-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='slides_no',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='ids',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(upload_to='teachers/'),
        ),
    ]
