# Generated by Django 6.0.5 on 2026-06-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_alter_teacher_image_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=100),
        ),
    ]
