# Generated by Django 6.0.5 on 2026-06-13 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_course_price_purchasedcourse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchasedCourse',
        ),
    ]
