# Generated by Django 6.0.6 on 2026-06-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='category',
            field=models.CharField(choices=[('Course', 'Course Problem'), ('Payment', 'Payment Problem'), ('Login', 'Login Problem'), ('Technical', 'Technical Issue'), ('AI', 'AI Doubt Solver'), ('Other', 'Other')], default='Other', max_length=30),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
